# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc60728d95b79fabc1623dd02dd918738b0a670805d3e5d99ccfaf58fd9c10e9a60b4ecd8567d6eee1c3301fa0fb942f88e3274909837860d2d50e6e3eb7e7b1

test:
  secret_key_base: 2f20b4316a55b6f5618e0eb1ad2fc9d5d8f393ff8ab4c1bc7e4e84e97c88f3c318f8493fc469b31a48fcbdcbdef0c5ca5a97aae34b0ace6b007d8b085eb2ed3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
